### PR TITLE
V0.2.1 fixes

### PR DESCRIPTION
**Pull request by bzkrouse**
Added warnings about tibbles per issue #7.

Fix for issue #15.  Note that the "clear files" button will also clear data from working environment.  Easy fix if we just want button to clear uploaded files.

### CODE REVIEW

**Comment by jwildfire** [comment]
Running this:
```
devtools::install_github('RhoInc/codebook',ref="278888b1846d76abcbda32f88e6c06f3ea49ea1e")
library(codebook)
codebook:::explorerApp()
```

Gives me this: 
screen shot 2017-10-13 at 8 10 02 am

screen shot 2017-10-13 at 8 12 14 am

Running 
```
test1<-iris
test2<-cars
codebook:::explorerApp()
```

Gives me the demo files:

screen shot 2017-10-13 at 8 14 26 am

**Comment by jwildfire** [comment]
Was using wrong commit! Everything looks great. Merging!

**Comment by jwildfire** [comment]
codebook bombs instead of loading demo data after initial load: 

screen shot 2017-10-13 at 8 31 56 am

**Comment by bzkrouse** [comment]
fixed - see latest commits!

**Pull request merged**
